import type { CarbonCategory } from "../types";

export type MerchantCarbonFactor = {
  category: CarbonCategory;
  factor_per_dollar: number;
  subcategory: string;
};

export type CategoryCarbonFactor = {
  category: CarbonCategory;
  factor_per_dollar: number;
};

export const MERCHANT_CARBON_MAP: Record<string, MerchantCarbonFactor> = {
  starbucks: { category: "food", factor_per_dollar: 0.35, subcategory: "coffee" },
  "dunkin": { category: "food", factor_per_dollar: 0.32, subcategory: "coffee" },
  "peets coffee": { category: "food", factor_per_dollar: 0.34, subcategory: "coffee" },
  "costa coffee": { category: "food", factor_per_dollar: 0.34, subcategory: "coffee" },
  "pret a manger": { category: "food", factor_per_dollar: 0.38, subcategory: "quick_service" },
  "panera bread": { category: "food", factor_per_dollar: 0.40, subcategory: "quick_service" },
  chipotle: { category: "food", factor_per_dollar: 0.45, subcategory: "fast_casual" },
  "sweetgreen": { category: "food", factor_per_dollar: 0.28, subcategory: "salad" },
  "cava": { category: "food", factor_per_dollar: 0.36, subcategory: "fast_casual" },
  mcdonalds: { category: "food", factor_per_dollar: 0.68, subcategory: "fast_food" },
  "burger king": { category: "food", factor_per_dollar: 0.66, subcategory: "fast_food" },
  "wendys": { category: "food", factor_per_dollar: 0.65, subcategory: "fast_food" },
  "taco bell": { category: "food", factor_per_dollar: 0.58, subcategory: "fast_food" },
  "kfc": { category: "food", factor_per_dollar: 0.62, subcategory: "fast_food" },
  "chick fil a": { category: "food", factor_per_dollar: 0.57, subcategory: "fast_food" },
  "subway": { category: "food", factor_per_dollar: 0.42, subcategory: "sandwiches" },
  "dominos": { category: "food", factor_per_dollar: 0.50, subcategory: "pizza" },
  "pizza hut": { category: "food", factor_per_dollar: 0.50, subcategory: "pizza" },
  "papa johns": { category: "food", factor_per_dollar: 0.50, subcategory: "pizza" },
  "doordash": { category: "food", factor_per_dollar: 0.52, subcategory: "delivery" },
  "ubereats": { category: "food", factor_per_dollar: 0.52, subcategory: "delivery" },
  "grubhub": { category: "food", factor_per_dollar: 0.52, subcategory: "delivery" },
  "instacart": { category: "food", factor_per_dollar: 0.30, subcategory: "grocery_delivery" },
  "whole foods": { category: "food", factor_per_dollar: 0.28, subcategory: "groceries" },
  "trader joes": { category: "food", factor_per_dollar: 0.26, subcategory: "groceries" },
  "kroger": { category: "food", factor_per_dollar: 0.28, subcategory: "groceries" },
  "safeway": { category: "food", factor_per_dollar: 0.28, subcategory: "groceries" },
  "albertsons": { category: "food", factor_per_dollar: 0.28, subcategory: "groceries" },
  "publix": { category: "food", factor_per_dollar: 0.28, subcategory: "groceries" },
  "aldi": { category: "food", factor_per_dollar: 0.25, subcategory: "groceries" },
  "lidl": { category: "food", factor_per_dollar: 0.25, subcategory: "groceries" },
  "tesco": { category: "food", factor_per_dollar: 0.27, subcategory: "groceries" },
  "sainsburys": { category: "food", factor_per_dollar: 0.27, subcategory: "groceries" },
  "carrefour": { category: "food", factor_per_dollar: 0.27, subcategory: "groceries" },
  "costco": { category: "shopping", factor_per_dollar: 0.27, subcategory: "warehouse" },
  walmart: { category: "shopping", factor_per_dollar: 0.25, subcategory: "grocery_general" },
  target: { category: "shopping", factor_per_dollar: 0.26, subcategory: "general" },
  amazon: { category: "shopping", factor_per_dollar: 0.30, subcategory: "general" },
  "amazon marketplace": { category: "shopping", factor_per_dollar: 0.30, subcategory: "general" },
  ebay: { category: "shopping", factor_per_dollar: 0.18, subcategory: "secondhand_general" },
  etsy: { category: "shopping", factor_per_dollar: 0.20, subcategory: "marketplace" },
  "best buy": { category: "shopping", factor_per_dollar: 0.35, subcategory: "electronics" },
  "apple": { category: "shopping", factor_per_dollar: 0.35, subcategory: "electronics" },
  "microsoft": { category: "shopping", factor_per_dollar: 0.20, subcategory: "software" },
  "google store": { category: "shopping", factor_per_dollar: 0.32, subcategory: "electronics" },
  "samsung": { category: "shopping", factor_per_dollar: 0.35, subcategory: "electronics" },
  "ikea": { category: "shopping", factor_per_dollar: 0.28, subcategory: "furniture" },
  "home depot": { category: "shopping", factor_per_dollar: 0.32, subcategory: "home_improvement" },
  "lowes": { category: "shopping", factor_per_dollar: 0.32, subcategory: "home_improvement" },
  "wayfair": { category: "shopping", factor_per_dollar: 0.31, subcategory: "furniture" },
  "hm": { category: "shopping", factor_per_dollar: 0.24, subcategory: "clothing" },
  "zara": { category: "shopping", factor_per_dollar: 0.25, subcategory: "clothing" },
  "uniqlo": { category: "shopping", factor_per_dollar: 0.22, subcategory: "clothing" },
  "gap": { category: "shopping", factor_per_dollar: 0.22, subcategory: "clothing" },
  "old navy": { category: "shopping", factor_per_dollar: 0.22, subcategory: "clothing" },
  "nike": { category: "shopping", factor_per_dollar: 0.27, subcategory: "apparel" },
  "adidas": { category: "shopping", factor_per_dollar: 0.27, subcategory: "apparel" },
  "patagonia": { category: "shopping", factor_per_dollar: 0.20, subcategory: "apparel" },
  "rei": { category: "shopping", factor_per_dollar: 0.24, subcategory: "outdoors" },
  "sephora": { category: "shopping", factor_per_dollar: 0.20, subcategory: "beauty" },
  "ulta": { category: "shopping", factor_per_dollar: 0.20, subcategory: "beauty" },
  "walgreens": { category: "shopping", factor_per_dollar: 0.18, subcategory: "pharmacy" },
  "cvs": { category: "shopping", factor_per_dollar: 0.18, subcategory: "pharmacy" },
  uber: { category: "transport", factor_per_dollar: 0.45, subcategory: "rideshare" },
  lyft: { category: "transport", factor_per_dollar: 0.45, subcategory: "rideshare" },
  "bolt": { category: "transport", factor_per_dollar: 0.40, subcategory: "rideshare" },
  "zipcar": { category: "transport", factor_per_dollar: 0.55, subcategory: "car_share" },
  "hertz": { category: "travel", factor_per_dollar: 0.55, subcategory: "car_rental" },
  "avis": { category: "travel", factor_per_dollar: 0.55, subcategory: "car_rental" },
  "enterprise": { category: "travel", factor_per_dollar: 0.55, subcategory: "car_rental" },
  "budget rent a car": { category: "travel", factor_per_dollar: 0.55, subcategory: "car_rental" },
  shell: { category: "transport", factor_per_dollar: 2.31, subcategory: "fuel" },
  chevron: { category: "transport", factor_per_dollar: 2.31, subcategory: "fuel" },
  exxon: { category: "transport", factor_per_dollar: 2.31, subcategory: "fuel" },
  mobil: { category: "transport", factor_per_dollar: 2.31, subcategory: "fuel" },
  bp: { category: "transport", factor_per_dollar: 2.31, subcategory: "fuel" },
  "7 eleven": { category: "transport", factor_per_dollar: 1.20, subcategory: "fuel_convenience" },
  "circle k": { category: "transport", factor_per_dollar: 1.20, subcategory: "fuel_convenience" },
  "speedway": { category: "transport", factor_per_dollar: 1.20, subcategory: "fuel_convenience" },
  "wawa": { category: "transport", factor_per_dollar: 1.00, subcategory: "fuel_convenience" },
  "tesla supercharger": { category: "transport", factor_per_dollar: 0.18, subcategory: "ev_charging" },
  "chargepoint": { category: "transport", factor_per_dollar: 0.18, subcategory: "ev_charging" },
  "evgo": { category: "transport", factor_per_dollar: 0.18, subcategory: "ev_charging" },
  "amtrak": { category: "transport", factor_per_dollar: 0.14, subcategory: "rail" },
  "mta": { category: "transport", factor_per_dollar: 0.12, subcategory: "public_transit" },
  "wmata": { category: "transport", factor_per_dollar: 0.12, subcategory: "public_transit" },
  "bart": { category: "transport", factor_per_dollar: 0.12, subcategory: "public_transit" },
  "tfl": { category: "transport", factor_per_dollar: 0.12, subcategory: "public_transit" },
  "lime": { category: "transport", factor_per_dollar: 0.08, subcategory: "micromobility" },
  "bird": { category: "transport", factor_per_dollar: 0.08, subcategory: "micromobility" },
  "united airlines": { category: "travel", factor_per_dollar: 1.20, subcategory: "flights" },
  "delta": { category: "travel", factor_per_dollar: 1.20, subcategory: "flights" },
  "american airlines": { category: "travel", factor_per_dollar: 1.20, subcategory: "flights" },
  "southwest": { category: "travel", factor_per_dollar: 1.15, subcategory: "flights" },
  "jetblue": { category: "travel", factor_per_dollar: 1.15, subcategory: "flights" },
  "alaska airlines": { category: "travel", factor_per_dollar: 1.15, subcategory: "flights" },
  "frontier airlines": { category: "travel", factor_per_dollar: 1.10, subcategory: "flights" },
  "spirit airlines": { category: "travel", factor_per_dollar: 1.10, subcategory: "flights" },
  "british airways": { category: "travel", factor_per_dollar: 1.20, subcategory: "flights" },
  "lufthansa": { category: "travel", factor_per_dollar: 1.20, subcategory: "flights" },
  "air france": { category: "travel", factor_per_dollar: 1.20, subcategory: "flights" },
  "klm": { category: "travel", factor_per_dollar: 1.20, subcategory: "flights" },
  "ryanair": { category: "travel", factor_per_dollar: 1.05, subcategory: "flights" },
  "easyjet": { category: "travel", factor_per_dollar: 1.05, subcategory: "flights" },
  "expedia": { category: "travel", factor_per_dollar: 0.90, subcategory: "travel_booking" },
  "booking com": { category: "travel", factor_per_dollar: 0.55, subcategory: "lodging" },
  "airbnb": { category: "travel", factor_per_dollar: 0.38, subcategory: "lodging" },
  "marriott": { category: "travel", factor_per_dollar: 0.45, subcategory: "hotel" },
  "hilton": { category: "travel", factor_per_dollar: 0.45, subcategory: "hotel" },
  "hyatt": { category: "travel", factor_per_dollar: 0.45, subcategory: "hotel" },
  "ihg": { category: "travel", factor_per_dollar: 0.45, subcategory: "hotel" },
  "accor": { category: "travel", factor_per_dollar: 0.45, subcategory: "hotel" },
  "pgande": { category: "home", factor_per_dollar: 0.85, subcategory: "electricity" },
  "con edison": { category: "home", factor_per_dollar: 0.85, subcategory: "electricity" },
  "duke energy": { category: "home", factor_per_dollar: 0.85, subcategory: "electricity" },
  "southern california edison": { category: "home", factor_per_dollar: 0.85, subcategory: "electricity" },
  "national grid": { category: "home", factor_per_dollar: 0.70, subcategory: "utility" },
  "xcel energy": { category: "home", factor_per_dollar: 0.80, subcategory: "utility" },
  "comcast": { category: "home", factor_per_dollar: 0.08, subcategory: "internet" },
  "xfinity": { category: "home", factor_per_dollar: 0.08, subcategory: "internet" },
  "verizon": { category: "home", factor_per_dollar: 0.08, subcategory: "telecom" },
  "att": { category: "home", factor_per_dollar: 0.08, subcategory: "telecom" },
  "tmobile": { category: "home", factor_per_dollar: 0.08, subcategory: "telecom" },
  "netflix": { category: "home", factor_per_dollar: 0.05, subcategory: "streaming" },
  "spotify": { category: "home", factor_per_dollar: 0.03, subcategory: "streaming" },
  "hulu": { category: "home", factor_per_dollar: 0.05, subcategory: "streaming" },
  "disney plus": { category: "home", factor_per_dollar: 0.05, subcategory: "streaming" },
  "youtube": { category: "home", factor_per_dollar: 0.05, subcategory: "streaming" }
};

export const CATEGORY_CARBON_MAP: Record<string, CategoryCarbonFactor> = {
  "Food and Drink": { category: "food", factor_per_dollar: 0.42 },
  "Food and Drink > Restaurants": { category: "food", factor_per_dollar: 0.42 },
  "Food and Drink > Fast Food": { category: "food", factor_per_dollar: 0.68 },
  "Food and Drink > Coffee Shop": { category: "food", factor_per_dollar: 0.35 },
  "Food and Drink > Bars": { category: "food", factor_per_dollar: 0.36 },
  "Food and Drink > Groceries": { category: "food", factor_per_dollar: 0.28 },
  "Food and Drink > Food Delivery": { category: "food", factor_per_dollar: 0.52 },
  "Travel": { category: "travel", factor_per_dollar: 0.60 },
  "Travel > Airlines": { category: "travel", factor_per_dollar: 1.20 },
  "Travel > Airports": { category: "travel", factor_per_dollar: 0.75 },
  "Travel > Car Rental": { category: "travel", factor_per_dollar: 0.55 },
  "Travel > Lodging": { category: "travel", factor_per_dollar: 0.45 },
  "Travel > Hotels": { category: "travel", factor_per_dollar: 0.45 },
  "Travel > Taxi": { category: "transport", factor_per_dollar: 0.45 },
  "Travel > Parking": { category: "transport", factor_per_dollar: 0.10 },
  "Travel > Public Transportation": { category: "transport", factor_per_dollar: 0.12 },
  "Transportation": { category: "transport", factor_per_dollar: 0.45 },
  "Transportation > Gas": { category: "transport", factor_per_dollar: 2.31 },
  "Transportation > Gas Stations": { category: "transport", factor_per_dollar: 2.31 },
  "Transportation > Rideshare": { category: "transport", factor_per_dollar: 0.45 },
  "Transportation > Taxis and Ride Shares": { category: "transport", factor_per_dollar: 0.45 },
  "Transportation > Public Transit": { category: "transport", factor_per_dollar: 0.12 },
  "Transportation > Train": { category: "transport", factor_per_dollar: 0.14 },
  "Transportation > Bus": { category: "transport", factor_per_dollar: 0.12 },
  "Transportation > Toll Roads": { category: "transport", factor_per_dollar: 0.30 },
  "Transportation > Parking": { category: "transport", factor_per_dollar: 0.10 },
  "Shops": { category: "shopping", factor_per_dollar: 0.25 },
  "Shops > Clothing": { category: "shopping", factor_per_dollar: 0.22 },
  "Shops > Electronics": { category: "shopping", factor_per_dollar: 0.35 },
  "Shops > Furniture": { category: "shopping", factor_per_dollar: 0.28 },
  "Shops > Hardware": { category: "shopping", factor_per_dollar: 0.32 },
  "Shops > Sporting Goods": { category: "shopping", factor_per_dollar: 0.24 },
  "Shops > Department Stores": { category: "shopping", factor_per_dollar: 0.26 },
  "Shops > Discount Stores": { category: "shopping", factor_per_dollar: 0.25 },
  "Shops > Supermarkets and Groceries": { category: "food", factor_per_dollar: 0.28 },
  "Shops > Pharmacies": { category: "shopping", factor_per_dollar: 0.18 },
  "Shops > Bookstores": { category: "shopping", factor_per_dollar: 0.16 },
  "Shops > Digital Purchase": { category: "shopping", factor_per_dollar: 0.08 },
  "Service": { category: "other", factor_per_dollar: 0.12 },
  "Service > Utilities": { category: "home", factor_per_dollar: 0.70 },
  "Service > Internet and Cable": { category: "home", factor_per_dollar: 0.08 },
  "Service > Telecommunications": { category: "home", factor_per_dollar: 0.08 },
  "Service > Cleaning": { category: "home", factor_per_dollar: 0.18 },
  "Service > Repair": { category: "shopping", factor_per_dollar: 0.16 },
  "Payment": { category: "other", factor_per_dollar: 0.05 },
  "Transfer": { category: "other", factor_per_dollar: 0.03 },
  "Recreation": { category: "other", factor_per_dollar: 0.16 },
  "Recreation > Gyms and Fitness Centers": { category: "home", factor_per_dollar: 0.10 },
  "Recreation > Entertainment": { category: "other", factor_per_dollar: 0.18 },
  "Recreation > Streaming Services": { category: "home", factor_per_dollar: 0.05 },
  "Healthcare": { category: "other", factor_per_dollar: 0.18 },
  "Healthcare > Pharmacies": { category: "shopping", factor_per_dollar: 0.18 },
  "Healthcare > Medical Services": { category: "other", factor_per_dollar: 0.20 },
  "Community": { category: "other", factor_per_dollar: 0.08 },
  "Community > Education": { category: "other", factor_per_dollar: 0.10 },
  "Community > Government": { category: "other", factor_per_dollar: 0.08 },
  "Community > Donations": { category: "other", factor_per_dollar: 0.02 },
  "Bank Fees": { category: "other", factor_per_dollar: 0.01 },
  "Interest": { category: "other", factor_per_dollar: 0.01 }
};
