INSERT INTO public.challenges (
  title,
  description,
  category,
  difficulty,
  carbon_save_kg,
  xp_reward,
  tips,
  icon,
  is_active
) VALUES
  (
    'Plant-Based Lunch',
    'Try a vegetarian or vegan lunch today',
    'food',
    'easy',
    2.5,
    15,
    ARRAY['Pick a lentil, bean, tofu, or vegetable-forward meal.', 'Keep it simple with a bowl, wrap, salad, or leftovers.'],
    'leaf',
    true
  ),
  (
    'Cook at Home',
    'Skip the takeout and cook a meal from scratch',
    'food',
    'easy',
    1.8,
    10,
    ARRAY['Use ingredients you already have first.', 'Cook an extra portion for tomorrow.'],
    'chef-hat',
    true
  ),
  (
    'Meatless Monday',
    'Go meat-free for the entire day',
    'food',
    'easy',
    3.2,
    20,
    ARRAY['Plan breakfast, lunch, and dinner before the day starts.', 'Swap meat with beans, tofu, eggs, or vegetables.'],
    'sprout',
    true
  ),
  (
    'Local Groceries',
    'Buy groceries from a local or farmers market',
    'food',
    'medium',
    1.5,
    15,
    ARRAY['Look for nearby seasonal produce.', 'Choose fewer packaged items when possible.'],
    'store',
    true
  ),
  (
    'Zero Food Waste Day',
    'Use up leftovers, don''t throw any food away',
    'food',
    'medium',
    2.0,
    20,
    ARRAY['Check the fridge before buying anything new.', 'Freeze anything you cannot use today.'],
    'recycle',
    true
  ),
  (
    'Batch Cook',
    'Prepare meals for the week to reduce daily cooking energy',
    'food',
    'medium',
    3.0,
    25,
    ARRAY['Cook grains, proteins, and vegetables in one session.', 'Store portions in reusable containers.'],
    'calendar-check',
    true
  ),
  (
    'Seasonal Eating',
    'Choose fruits and vegetables that are in season',
    'food',
    'easy',
    1.2,
    10,
    ARRAY['Choose produce grown closer to home.', 'Build one meal around seasonal ingredients.'],
    'apple',
    true
  ),
  (
    'Bring Your Own Coffee',
    'Bring a reusable cup instead of buying disposable',
    'food',
    'easy',
    0.5,
    5,
    ARRAY['Keep a clean reusable cup in your bag.', 'Choose a cafe that accepts personal cups.'],
    'coffee',
    true
  ),
  (
    'Walk or Bike Today',
    'Use human power for your commute or errands',
    'transport',
    'easy',
    4.2,
    20,
    ARRAY['Start with one short trip.', 'Use a safe, familiar route.'],
    'bike',
    true
  ),
  (
    'Public Transit Day',
    'Take the bus, train, or subway instead of driving',
    'transport',
    'easy',
    3.5,
    15,
    ARRAY['Check schedules before leaving.', 'Bring headphones, a book, or downloaded reading.'],
    'train',
    true
  ),
  (
    'Carpool Challenge',
    'Share a ride with a colleague or neighbor',
    'transport',
    'medium',
    2.8,
    20,
    ARRAY['Ask one person with a similar route.', 'Coordinate pickup and dropoff ahead of time.'],
    'users',
    true
  ),
  (
    'Work From Home',
    'Skip the commute entirely if possible',
    'transport',
    'easy',
    5.0,
    15,
    ARRAY['Group meetings into remote-friendly blocks.', 'Use the saved commute time for a walk or reset.'],
    'house',
    true
  ),
  (
    'No-Drive Day',
    'Don''t use a personal vehicle for 24 hours',
    'transport',
    'medium',
    6.5,
    25,
    ARRAY['Plan errands around walking, biking, transit, or delivery consolidation.', 'Move one non-urgent trip to another day.'],
    'ban',
    true
  ),
  (
    'Combine Errands',
    'Plan your errands to minimize driving trips',
    'transport',
    'easy',
    2.0,
    10,
    ARRAY['List every stop before leaving.', 'Choose the shortest loop instead of separate trips.'],
    'route',
    true
  ),
  (
    'Eco-Driving',
    'Drive smoothly - no harsh braking or rapid acceleration',
    'transport',
    'medium',
    1.5,
    15,
    ARRAY['Accelerate gradually.', 'Keep tires inflated and avoid unnecessary idling.'],
    'gauge',
    true
  ),
  (
    'Thermostat Adjust',
    'Lower heating by 1°C or raise cooling by 1°C',
    'home',
    'easy',
    3.0,
    15,
    ARRAY['Adjust by one degree and give your body time to adapt.', 'Use layers, fans, or shade to stay comfortable.'],
    'thermometer',
    true
  ),
  (
    'Unplug Standby Devices',
    'Unplug chargers and devices not in use',
    'home',
    'easy',
    0.8,
    5,
    ARRAY['Start with chargers, game consoles, and spare electronics.', 'Use a power strip for easy switching.'],
    'plug',
    true
  ),
  (
    'Short Shower',
    'Keep your shower under 5 minutes',
    'home',
    'easy',
    1.2,
    10,
    ARRAY['Set a five-minute timer.', 'Turn water off while lathering if comfortable.'],
    'shower-head',
    true
  ),
  (
    'Air Dry Laundry',
    'Skip the dryer and hang clothes to dry',
    'home',
    'medium',
    2.5,
    15,
    ARRAY['Use a rack, line, or hangers.', 'Start with lightweight clothes that dry quickly.'],
    'shirt',
    true
  ),
  (
    'LED Switch',
    'Replace one traditional bulb with an LED',
    'home',
    'easy',
    0.5,
    5,
    ARRAY['Pick a frequently used light first.', 'Recycle old bulbs according to local rules.'],
    'lightbulb',
    true
  ),
  (
    'Cold Wash',
    'Wash clothes in cold water instead of hot',
    'home',
    'easy',
    1.8,
    10,
    ARRAY['Use cold-water detergent if available.', 'Reserve hot water for sanitizing needs.'],
    'washing-machine',
    true
  ),
  (
    'No-Buy Day',
    'Don''t purchase anything non-essential today',
    'shopping',
    'easy',
    3.5,
    15,
    ARRAY['Pause impulse purchases for 24 hours.', 'Add wanted items to a list instead of buying immediately.'],
    'shopping-bag',
    true
  ),
  (
    'Secondhand Find',
    'Buy something secondhand instead of new',
    'shopping',
    'medium',
    4.0,
    25,
    ARRAY['Check thrift stores, resale apps, or community groups.', 'Search for quality items that will last.'],
    'repeat',
    true
  ),
  (
    'Repair Don''t Replace',
    'Fix something broken instead of buying new',
    'shopping',
    'hard',
    5.0,
    35,
    ARRAY['Look up a repair guide before replacing the item.', 'Try a local repair shop for harder fixes.'],
    'wrench',
    true
  ),
  (
    'Reusable Bags',
    'Bring your own bags for all shopping',
    'shopping',
    'easy',
    0.3,
    5,
    ARRAY['Keep bags by the door, in your car, or in your backpack.', 'Use any durable bag you already own.'],
    'shopping-basket',
    true
  ),
  (
    'Digital Over Physical',
    'Choose digital versions - tickets, receipts, books',
    'shopping',
    'easy',
    1.0,
    10,
    ARRAY['Choose email receipts when offered.', 'Use digital tickets and passes where accepted.'],
    'smartphone',
    true
  ),
  (
    'Digital Detox Hour',
    '1 hour of no screens - saves energy and mental health',
    'lifestyle',
    'easy',
    0.2,
    10,
    ARRAY['Charge devices outside the room.', 'Use the hour for a walk, reading, or cooking.'],
    'moon',
    true
  ),
  (
    'Carbon Conversation',
    'Talk to someone about climate action today',
    'lifestyle',
    'medium',
    0,
    20,
    ARRAY['Share one action that worked for you.', 'Ask what climate-friendly habit they already enjoy.'],
    'messages-square',
    true
  ),
  (
    'Learn Your Impact',
    'Read one article about carbon footprint reduction',
    'lifestyle',
    'easy',
    0,
    10,
    ARRAY['Choose a practical article with actions you can try.', 'Save one idea for tomorrow.'],
    'book-open',
    true
  ),
  (
    'Offset Research',
    'Research a verified carbon offset project',
    'lifestyle',
    'medium',
    0,
    15,
    ARRAY['Look for third-party verification.', 'Compare permanence, additionality, and transparency.'],
    'search',
    true
  );
