/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectBankRouteImport } from './routes/connect-bank'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiStreaksRouteImport } from './routes/api.streaks'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as ApiLevelRouteImport } from './routes/api.level'
import { Route as ApiAchievementsRouteImport } from './routes/api.achievements'
import { Route as ApiTeamsMyTeamsRouteImport } from './routes/api.teams.my-teams'
import { Route as ApiTeamsCreateRouteImport } from './routes/api.teams.create'
import { Route as ApiTeamsIdRouteImport } from './routes/api.teams.$id'
import { Route as ApiProfileCarbonAgeRouteImport } from './routes/api.profile.carbon-age'
import { Route as ApiPlaidSyncTransactionsRouteImport } from './routes/api.plaid.sync-transactions'
import { Route as ApiPlaidExchangeTokenRouteImport } from './routes/api.plaid.exchange-token'
import { Route as ApiPlaidCreateLinkTokenRouteImport } from './routes/api.plaid.create-link-token'
import { Route as ApiOnboardingQuizRouteImport } from './routes/api.onboarding.quiz'
import { Route as ApiOnboardingCompleteRouteImport } from './routes/api.onboarding.complete'
import { Route as ApiImpactTotalRouteImport } from './routes/api.impact.total'
import { Route as ApiImpactEquivalenciesRouteImport } from './routes/api.impact.equivalencies'
import { Route as ApiCopilotSuggestionsRouteImport } from './routes/api.copilot.suggestions'
import { Route as ApiCopilotHistoryRouteImport } from './routes/api.copilot.history'
import { Route as ApiCopilotChatRouteImport } from './routes/api.copilot.chat'
import { Route as ApiChallengesTodayRouteImport } from './routes/api.challenges.today'
import { Route as ApiChallengesLibraryRouteImport } from './routes/api.challenges.library'
import { Route as ApiChallengesHistoryRouteImport } from './routes/api.challenges.history'
import { Route as ApiCarbonTrendsRouteImport } from './routes/api.carbon.trends'
import { Route as ApiCarbonTransactionsRouteImport } from './routes/api.carbon.transactions'
import { Route as ApiCarbonDashboardRouteImport } from './routes/api.carbon.dashboard'
import { Route as ApiCarbonCompareRouteImport } from './routes/api.carbon.compare'
import { Route as ApiTeamsJoinInviteCodeRouteImport } from './routes/api.teams.join.$inviteCode'
import { Route as ApiTeamsIdLeaderboardRouteImport } from './routes/api.teams.$id.leaderboard'
import { Route as ApiPlaidDisconnectIdRouteImport } from './routes/api.plaid.disconnect.$id'
import { Route as ApiChallengesIdActionRouteImport } from './routes/api.challenges.$id.$action'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectBankRoute = ConnectBankRouteImport.update({
  id: '/connect-bank',
  path: '/connect-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreaksRoute = ApiStreaksRouteImport.update({
  id: '/api/streaks',
  path: '/api/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLevelRoute = ApiLevelRouteImport.update({
  id: '/api/level',
  path: '/api/level',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAchievementsRoute = ApiAchievementsRouteImport.update({
  id: '/api/achievements',
  path: '/api/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsMyTeamsRoute = ApiTeamsMyTeamsRouteImport.update({
  id: '/api/teams/my-teams',
  path: '/api/teams/my-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsCreateRoute = ApiTeamsCreateRouteImport.update({
  id: '/api/teams/create',
  path: '/api/teams/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsIdRoute = ApiTeamsIdRouteImport.update({
  id: '/api/teams/$id',
  path: '/api/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileCarbonAgeRoute = ApiProfileCarbonAgeRouteImport.update({
  id: '/carbon-age',
  path: '/carbon-age',
  getParentRoute: () => ApiProfileRoute,
} as any)
const ApiPlaidSyncTransactionsRoute =
  ApiPlaidSyncTransactionsRouteImport.update({
    id: '/api/plaid/sync-transactions',
    path: '/api/plaid/sync-transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlaidExchangeTokenRoute = ApiPlaidExchangeTokenRouteImport.update({
  id: '/api/plaid/exchange-token',
  path: '/api/plaid/exchange-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaidCreateLinkTokenRoute = ApiPlaidCreateLinkTokenRouteImport.update({
  id: '/api/plaid/create-link-token',
  path: '/api/plaid/create-link-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingQuizRoute = ApiOnboardingQuizRouteImport.update({
  id: '/api/onboarding/quiz',
  path: '/api/onboarding/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingCompleteRoute = ApiOnboardingCompleteRouteImport.update({
  id: '/api/onboarding/complete',
  path: '/api/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImpactTotalRoute = ApiImpactTotalRouteImport.update({
  id: '/api/impact/total',
  path: '/api/impact/total',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImpactEquivalenciesRoute = ApiImpactEquivalenciesRouteImport.update({
  id: '/api/impact/equivalencies',
  path: '/api/impact/equivalencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotSuggestionsRoute = ApiCopilotSuggestionsRouteImport.update({
  id: '/api/copilot/suggestions',
  path: '/api/copilot/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotHistoryRoute = ApiCopilotHistoryRouteImport.update({
  id: '/api/copilot/history',
  path: '/api/copilot/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotChatRoute = ApiCopilotChatRouteImport.update({
  id: '/api/copilot/chat',
  path: '/api/copilot/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesTodayRoute = ApiChallengesTodayRouteImport.update({
  id: '/api/challenges/today',
  path: '/api/challenges/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesLibraryRoute = ApiChallengesLibraryRouteImport.update({
  id: '/api/challenges/library',
  path: '/api/challenges/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesHistoryRoute = ApiChallengesHistoryRouteImport.update({
  id: '/api/challenges/history',
  path: '/api/challenges/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarbonTrendsRoute = ApiCarbonTrendsRouteImport.update({
  id: '/api/carbon/trends',
  path: '/api/carbon/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarbonTransactionsRoute = ApiCarbonTransactionsRouteImport.update({
  id: '/api/carbon/transactions',
  path: '/api/carbon/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarbonDashboardRoute = ApiCarbonDashboardRouteImport.update({
  id: '/api/carbon/dashboard',
  path: '/api/carbon/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarbonCompareRoute = ApiCarbonCompareRouteImport.update({
  id: '/api/carbon/compare',
  path: '/api/carbon/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsJoinInviteCodeRoute = ApiTeamsJoinInviteCodeRouteImport.update({
  id: '/api/teams/join/$inviteCode',
  path: '/api/teams/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsIdLeaderboardRoute = ApiTeamsIdLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => ApiTeamsIdRoute,
} as any)
const ApiPlaidDisconnectIdRoute = ApiPlaidDisconnectIdRouteImport.update({
  id: '/api/plaid/disconnect/$id',
  path: '/api/plaid/disconnect/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesIdActionRoute = ApiChallengesIdActionRouteImport.update({
  id: '/api/challenges/$id/$action',
  path: '/api/challenges/$id/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/api/achievements': typeof ApiAchievementsRoute
  '/api/level': typeof ApiLevelRoute
  '/api/profile': typeof ApiProfileRouteWithChildren
  '/api/streaks': typeof ApiStreaksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$id': typeof TeamsIdRoute
  '/api/carbon/compare': typeof ApiCarbonCompareRoute
  '/api/carbon/dashboard': typeof ApiCarbonDashboardRoute
  '/api/carbon/transactions': typeof ApiCarbonTransactionsRoute
  '/api/carbon/trends': typeof ApiCarbonTrendsRoute
  '/api/challenges/history': typeof ApiChallengesHistoryRoute
  '/api/challenges/library': typeof ApiChallengesLibraryRoute
  '/api/challenges/today': typeof ApiChallengesTodayRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copilot/suggestions': typeof ApiCopilotSuggestionsRoute
  '/api/impact/equivalencies': typeof ApiImpactEquivalenciesRoute
  '/api/impact/total': typeof ApiImpactTotalRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/quiz': typeof ApiOnboardingQuizRoute
  '/api/plaid/create-link-token': typeof ApiPlaidCreateLinkTokenRoute
  '/api/plaid/exchange-token': typeof ApiPlaidExchangeTokenRoute
  '/api/plaid/sync-transactions': typeof ApiPlaidSyncTransactionsRoute
  '/api/profile/carbon-age': typeof ApiProfileCarbonAgeRoute
  '/api/teams/$id': typeof ApiTeamsIdRouteWithChildren
  '/api/teams/create': typeof ApiTeamsCreateRoute
  '/api/teams/my-teams': typeof ApiTeamsMyTeamsRoute
  '/api/challenges/$id/$action': typeof ApiChallengesIdActionRoute
  '/api/plaid/disconnect/$id': typeof ApiPlaidDisconnectIdRoute
  '/api/teams/$id/leaderboard': typeof ApiTeamsIdLeaderboardRoute
  '/api/teams/join/$inviteCode': typeof ApiTeamsJoinInviteCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/api/achievements': typeof ApiAchievementsRoute
  '/api/level': typeof ApiLevelRoute
  '/api/profile': typeof ApiProfileRouteWithChildren
  '/api/streaks': typeof ApiStreaksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$id': typeof TeamsIdRoute
  '/api/carbon/compare': typeof ApiCarbonCompareRoute
  '/api/carbon/dashboard': typeof ApiCarbonDashboardRoute
  '/api/carbon/transactions': typeof ApiCarbonTransactionsRoute
  '/api/carbon/trends': typeof ApiCarbonTrendsRoute
  '/api/challenges/history': typeof ApiChallengesHistoryRoute
  '/api/challenges/library': typeof ApiChallengesLibraryRoute
  '/api/challenges/today': typeof ApiChallengesTodayRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copilot/suggestions': typeof ApiCopilotSuggestionsRoute
  '/api/impact/equivalencies': typeof ApiImpactEquivalenciesRoute
  '/api/impact/total': typeof ApiImpactTotalRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/quiz': typeof ApiOnboardingQuizRoute
  '/api/plaid/create-link-token': typeof ApiPlaidCreateLinkTokenRoute
  '/api/plaid/exchange-token': typeof ApiPlaidExchangeTokenRoute
  '/api/plaid/sync-transactions': typeof ApiPlaidSyncTransactionsRoute
  '/api/profile/carbon-age': typeof ApiProfileCarbonAgeRoute
  '/api/teams/$id': typeof ApiTeamsIdRouteWithChildren
  '/api/teams/create': typeof ApiTeamsCreateRoute
  '/api/teams/my-teams': typeof ApiTeamsMyTeamsRoute
  '/api/challenges/$id/$action': typeof ApiChallengesIdActionRoute
  '/api/plaid/disconnect/$id': typeof ApiPlaidDisconnectIdRoute
  '/api/teams/$id/leaderboard': typeof ApiTeamsIdLeaderboardRoute
  '/api/teams/join/$inviteCode': typeof ApiTeamsJoinInviteCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/api/achievements': typeof ApiAchievementsRoute
  '/api/level': typeof ApiLevelRoute
  '/api/profile': typeof ApiProfileRouteWithChildren
  '/api/streaks': typeof ApiStreaksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$id': typeof TeamsIdRoute
  '/api/carbon/compare': typeof ApiCarbonCompareRoute
  '/api/carbon/dashboard': typeof ApiCarbonDashboardRoute
  '/api/carbon/transactions': typeof ApiCarbonTransactionsRoute
  '/api/carbon/trends': typeof ApiCarbonTrendsRoute
  '/api/challenges/history': typeof ApiChallengesHistoryRoute
  '/api/challenges/library': typeof ApiChallengesLibraryRoute
  '/api/challenges/today': typeof ApiChallengesTodayRoute
  '/api/copilot/chat': typeof ApiCopilotChatRoute
  '/api/copilot/history': typeof ApiCopilotHistoryRoute
  '/api/copilot/suggestions': typeof ApiCopilotSuggestionsRoute
  '/api/impact/equivalencies': typeof ApiImpactEquivalenciesRoute
  '/api/impact/total': typeof ApiImpactTotalRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/quiz': typeof ApiOnboardingQuizRoute
  '/api/plaid/create-link-token': typeof ApiPlaidCreateLinkTokenRoute
  '/api/plaid/exchange-token': typeof ApiPlaidExchangeTokenRoute
  '/api/plaid/sync-transactions': typeof ApiPlaidSyncTransactionsRoute
  '/api/profile/carbon-age': typeof ApiProfileCarbonAgeRoute
  '/api/teams/$id': typeof ApiTeamsIdRouteWithChildren
  '/api/teams/create': typeof ApiTeamsCreateRoute
  '/api/teams/my-teams': typeof ApiTeamsMyTeamsRoute
  '/api/challenges/$id/$action': typeof ApiChallengesIdActionRoute
  '/api/plaid/disconnect/$id': typeof ApiPlaidDisconnectIdRoute
  '/api/teams/$id/leaderboard': typeof ApiTeamsIdLeaderboardRoute
  '/api/teams/join/$inviteCode': typeof ApiTeamsJoinInviteCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/connect-bank'
    | '/dashboard'
    | '/home'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/success'
    | '/teams'
    | '/transactions'
    | '/api/achievements'
    | '/api/level'
    | '/api/profile'
    | '/api/streaks'
    | '/auth/callback'
    | '/teams/$id'
    | '/api/carbon/compare'
    | '/api/carbon/dashboard'
    | '/api/carbon/transactions'
    | '/api/carbon/trends'
    | '/api/challenges/history'
    | '/api/challenges/library'
    | '/api/challenges/today'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copilot/suggestions'
    | '/api/impact/equivalencies'
    | '/api/impact/total'
    | '/api/onboarding/complete'
    | '/api/onboarding/quiz'
    | '/api/plaid/create-link-token'
    | '/api/plaid/exchange-token'
    | '/api/plaid/sync-transactions'
    | '/api/profile/carbon-age'
    | '/api/teams/$id'
    | '/api/teams/create'
    | '/api/teams/my-teams'
    | '/api/challenges/$id/$action'
    | '/api/plaid/disconnect/$id'
    | '/api/teams/$id/leaderboard'
    | '/api/teams/join/$inviteCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/connect-bank'
    | '/dashboard'
    | '/home'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/success'
    | '/teams'
    | '/transactions'
    | '/api/achievements'
    | '/api/level'
    | '/api/profile'
    | '/api/streaks'
    | '/auth/callback'
    | '/teams/$id'
    | '/api/carbon/compare'
    | '/api/carbon/dashboard'
    | '/api/carbon/transactions'
    | '/api/carbon/trends'
    | '/api/challenges/history'
    | '/api/challenges/library'
    | '/api/challenges/today'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copilot/suggestions'
    | '/api/impact/equivalencies'
    | '/api/impact/total'
    | '/api/onboarding/complete'
    | '/api/onboarding/quiz'
    | '/api/plaid/create-link-token'
    | '/api/plaid/exchange-token'
    | '/api/plaid/sync-transactions'
    | '/api/profile/carbon-age'
    | '/api/teams/$id'
    | '/api/teams/create'
    | '/api/teams/my-teams'
    | '/api/challenges/$id/$action'
    | '/api/plaid/disconnect/$id'
    | '/api/teams/$id/leaderboard'
    | '/api/teams/join/$inviteCode'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/connect-bank'
    | '/dashboard'
    | '/home'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/success'
    | '/teams'
    | '/transactions'
    | '/api/achievements'
    | '/api/level'
    | '/api/profile'
    | '/api/streaks'
    | '/auth/callback'
    | '/teams/$id'
    | '/api/carbon/compare'
    | '/api/carbon/dashboard'
    | '/api/carbon/transactions'
    | '/api/carbon/trends'
    | '/api/challenges/history'
    | '/api/challenges/library'
    | '/api/challenges/today'
    | '/api/copilot/chat'
    | '/api/copilot/history'
    | '/api/copilot/suggestions'
    | '/api/impact/equivalencies'
    | '/api/impact/total'
    | '/api/onboarding/complete'
    | '/api/onboarding/quiz'
    | '/api/plaid/create-link-token'
    | '/api/plaid/exchange-token'
    | '/api/plaid/sync-transactions'
    | '/api/profile/carbon-age'
    | '/api/teams/$id'
    | '/api/teams/create'
    | '/api/teams/my-teams'
    | '/api/challenges/$id/$action'
    | '/api/plaid/disconnect/$id'
    | '/api/teams/$id/leaderboard'
    | '/api/teams/join/$inviteCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  ConnectBankRoute: typeof ConnectBankRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SuccessRoute: typeof SuccessRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
  ApiAchievementsRoute: typeof ApiAchievementsRoute
  ApiLevelRoute: typeof ApiLevelRoute
  ApiProfileRoute: typeof ApiProfileRouteWithChildren
  ApiStreaksRoute: typeof ApiStreaksRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiCarbonCompareRoute: typeof ApiCarbonCompareRoute
  ApiCarbonDashboardRoute: typeof ApiCarbonDashboardRoute
  ApiCarbonTransactionsRoute: typeof ApiCarbonTransactionsRoute
  ApiCarbonTrendsRoute: typeof ApiCarbonTrendsRoute
  ApiChallengesHistoryRoute: typeof ApiChallengesHistoryRoute
  ApiChallengesLibraryRoute: typeof ApiChallengesLibraryRoute
  ApiChallengesTodayRoute: typeof ApiChallengesTodayRoute
  ApiCopilotChatRoute: typeof ApiCopilotChatRoute
  ApiCopilotHistoryRoute: typeof ApiCopilotHistoryRoute
  ApiCopilotSuggestionsRoute: typeof ApiCopilotSuggestionsRoute
  ApiImpactEquivalenciesRoute: typeof ApiImpactEquivalenciesRoute
  ApiImpactTotalRoute: typeof ApiImpactTotalRoute
  ApiOnboardingCompleteRoute: typeof ApiOnboardingCompleteRoute
  ApiOnboardingQuizRoute: typeof ApiOnboardingQuizRoute
  ApiPlaidCreateLinkTokenRoute: typeof ApiPlaidCreateLinkTokenRoute
  ApiPlaidExchangeTokenRoute: typeof ApiPlaidExchangeTokenRoute
  ApiPlaidSyncTransactionsRoute: typeof ApiPlaidSyncTransactionsRoute
  ApiTeamsIdRoute: typeof ApiTeamsIdRouteWithChildren
  ApiTeamsCreateRoute: typeof ApiTeamsCreateRoute
  ApiTeamsMyTeamsRoute: typeof ApiTeamsMyTeamsRoute
  ApiChallengesIdActionRoute: typeof ApiChallengesIdActionRoute
  ApiPlaidDisconnectIdRoute: typeof ApiPlaidDisconnectIdRoute
  ApiTeamsJoinInviteCodeRoute: typeof ApiTeamsJoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-bank': {
      id: '/connect-bank'
      path: '/connect-bank'
      fullPath: '/connect-bank'
      preLoaderRoute: typeof ConnectBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streaks': {
      id: '/api/streaks'
      path: '/api/streaks'
      fullPath: '/api/streaks'
      preLoaderRoute: typeof ApiStreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/level': {
      id: '/api/level'
      path: '/api/level'
      fullPath: '/api/level'
      preLoaderRoute: typeof ApiLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/achievements': {
      id: '/api/achievements'
      path: '/api/achievements'
      fullPath: '/api/achievements'
      preLoaderRoute: typeof ApiAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams/my-teams': {
      id: '/api/teams/my-teams'
      path: '/api/teams/my-teams'
      fullPath: '/api/teams/my-teams'
      preLoaderRoute: typeof ApiTeamsMyTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams/create': {
      id: '/api/teams/create'
      path: '/api/teams/create'
      fullPath: '/api/teams/create'
      preLoaderRoute: typeof ApiTeamsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams/$id': {
      id: '/api/teams/$id'
      path: '/api/teams/$id'
      fullPath: '/api/teams/$id'
      preLoaderRoute: typeof ApiTeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile/carbon-age': {
      id: '/api/profile/carbon-age'
      path: '/carbon-age'
      fullPath: '/api/profile/carbon-age'
      preLoaderRoute: typeof ApiProfileCarbonAgeRouteImport
      parentRoute: typeof ApiProfileRoute
    }
    '/api/plaid/sync-transactions': {
      id: '/api/plaid/sync-transactions'
      path: '/api/plaid/sync-transactions'
      fullPath: '/api/plaid/sync-transactions'
      preLoaderRoute: typeof ApiPlaidSyncTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plaid/exchange-token': {
      id: '/api/plaid/exchange-token'
      path: '/api/plaid/exchange-token'
      fullPath: '/api/plaid/exchange-token'
      preLoaderRoute: typeof ApiPlaidExchangeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plaid/create-link-token': {
      id: '/api/plaid/create-link-token'
      path: '/api/plaid/create-link-token'
      fullPath: '/api/plaid/create-link-token'
      preLoaderRoute: typeof ApiPlaidCreateLinkTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/quiz': {
      id: '/api/onboarding/quiz'
      path: '/api/onboarding/quiz'
      fullPath: '/api/onboarding/quiz'
      preLoaderRoute: typeof ApiOnboardingQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/complete': {
      id: '/api/onboarding/complete'
      path: '/api/onboarding/complete'
      fullPath: '/api/onboarding/complete'
      preLoaderRoute: typeof ApiOnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/impact/total': {
      id: '/api/impact/total'
      path: '/api/impact/total'
      fullPath: '/api/impact/total'
      preLoaderRoute: typeof ApiImpactTotalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/impact/equivalencies': {
      id: '/api/impact/equivalencies'
      path: '/api/impact/equivalencies'
      fullPath: '/api/impact/equivalencies'
      preLoaderRoute: typeof ApiImpactEquivalenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/suggestions': {
      id: '/api/copilot/suggestions'
      path: '/api/copilot/suggestions'
      fullPath: '/api/copilot/suggestions'
      preLoaderRoute: typeof ApiCopilotSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/history': {
      id: '/api/copilot/history'
      path: '/api/copilot/history'
      fullPath: '/api/copilot/history'
      preLoaderRoute: typeof ApiCopilotHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot/chat': {
      id: '/api/copilot/chat'
      path: '/api/copilot/chat'
      fullPath: '/api/copilot/chat'
      preLoaderRoute: typeof ApiCopilotChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/today': {
      id: '/api/challenges/today'
      path: '/api/challenges/today'
      fullPath: '/api/challenges/today'
      preLoaderRoute: typeof ApiChallengesTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/library': {
      id: '/api/challenges/library'
      path: '/api/challenges/library'
      fullPath: '/api/challenges/library'
      preLoaderRoute: typeof ApiChallengesLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/history': {
      id: '/api/challenges/history'
      path: '/api/challenges/history'
      fullPath: '/api/challenges/history'
      preLoaderRoute: typeof ApiChallengesHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carbon/trends': {
      id: '/api/carbon/trends'
      path: '/api/carbon/trends'
      fullPath: '/api/carbon/trends'
      preLoaderRoute: typeof ApiCarbonTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carbon/transactions': {
      id: '/api/carbon/transactions'
      path: '/api/carbon/transactions'
      fullPath: '/api/carbon/transactions'
      preLoaderRoute: typeof ApiCarbonTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carbon/dashboard': {
      id: '/api/carbon/dashboard'
      path: '/api/carbon/dashboard'
      fullPath: '/api/carbon/dashboard'
      preLoaderRoute: typeof ApiCarbonDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carbon/compare': {
      id: '/api/carbon/compare'
      path: '/api/carbon/compare'
      fullPath: '/api/carbon/compare'
      preLoaderRoute: typeof ApiCarbonCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams/join/$inviteCode': {
      id: '/api/teams/join/$inviteCode'
      path: '/api/teams/join/$inviteCode'
      fullPath: '/api/teams/join/$inviteCode'
      preLoaderRoute: typeof ApiTeamsJoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams/$id/leaderboard': {
      id: '/api/teams/$id/leaderboard'
      path: '/leaderboard'
      fullPath: '/api/teams/$id/leaderboard'
      preLoaderRoute: typeof ApiTeamsIdLeaderboardRouteImport
      parentRoute: typeof ApiTeamsIdRoute
    }
    '/api/plaid/disconnect/$id': {
      id: '/api/plaid/disconnect/$id'
      path: '/api/plaid/disconnect/$id'
      fullPath: '/api/plaid/disconnect/$id'
      preLoaderRoute: typeof ApiPlaidDisconnectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges/$id/$action': {
      id: '/api/challenges/$id/$action'
      path: '/api/challenges/$id/$action'
      fullPath: '/api/challenges/$id/$action'
      preLoaderRoute: typeof ApiChallengesIdActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface ApiProfileRouteChildren {
  ApiProfileCarbonAgeRoute: typeof ApiProfileCarbonAgeRoute
}

const ApiProfileRouteChildren: ApiProfileRouteChildren = {
  ApiProfileCarbonAgeRoute: ApiProfileCarbonAgeRoute,
}

const ApiProfileRouteWithChildren = ApiProfileRoute._addFileChildren(
  ApiProfileRouteChildren,
)

interface ApiTeamsIdRouteChildren {
  ApiTeamsIdLeaderboardRoute: typeof ApiTeamsIdLeaderboardRoute
}

const ApiTeamsIdRouteChildren: ApiTeamsIdRouteChildren = {
  ApiTeamsIdLeaderboardRoute: ApiTeamsIdLeaderboardRoute,
}

const ApiTeamsIdRouteWithChildren = ApiTeamsIdRoute._addFileChildren(
  ApiTeamsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  ConnectBankRoute: ConnectBankRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SuccessRoute: SuccessRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
  ApiAchievementsRoute: ApiAchievementsRoute,
  ApiLevelRoute: ApiLevelRoute,
  ApiProfileRoute: ApiProfileRouteWithChildren,
  ApiStreaksRoute: ApiStreaksRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiCarbonCompareRoute: ApiCarbonCompareRoute,
  ApiCarbonDashboardRoute: ApiCarbonDashboardRoute,
  ApiCarbonTransactionsRoute: ApiCarbonTransactionsRoute,
  ApiCarbonTrendsRoute: ApiCarbonTrendsRoute,
  ApiChallengesHistoryRoute: ApiChallengesHistoryRoute,
  ApiChallengesLibraryRoute: ApiChallengesLibraryRoute,
  ApiChallengesTodayRoute: ApiChallengesTodayRoute,
  ApiCopilotChatRoute: ApiCopilotChatRoute,
  ApiCopilotHistoryRoute: ApiCopilotHistoryRoute,
  ApiCopilotSuggestionsRoute: ApiCopilotSuggestionsRoute,
  ApiImpactEquivalenciesRoute: ApiImpactEquivalenciesRoute,
  ApiImpactTotalRoute: ApiImpactTotalRoute,
  ApiOnboardingCompleteRoute: ApiOnboardingCompleteRoute,
  ApiOnboardingQuizRoute: ApiOnboardingQuizRoute,
  ApiPlaidCreateLinkTokenRoute: ApiPlaidCreateLinkTokenRoute,
  ApiPlaidExchangeTokenRoute: ApiPlaidExchangeTokenRoute,
  ApiPlaidSyncTransactionsRoute: ApiPlaidSyncTransactionsRoute,
  ApiTeamsIdRoute: ApiTeamsIdRouteWithChildren,
  ApiTeamsCreateRoute: ApiTeamsCreateRoute,
  ApiTeamsMyTeamsRoute: ApiTeamsMyTeamsRoute,
  ApiChallengesIdActionRoute: ApiChallengesIdActionRoute,
  ApiPlaidDisconnectIdRoute: ApiPlaidDisconnectIdRoute,
  ApiTeamsJoinInviteCodeRoute: ApiTeamsJoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
