/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectBankRouteImport } from './routes/connect-bank'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectBankRoute = ConnectBankRouteImport.update({
  id: '/connect-bank',
  path: '/connect-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$id': typeof TeamsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$id': typeof TeamsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/connect-bank': typeof ConnectBankRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/success': typeof SuccessRoute
  '/teams': typeof TeamsRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/teams/$id': typeof TeamsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/connect-bank'
    | '/dashboard'
    | '/home'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/success'
    | '/teams'
    | '/transactions'
    | '/auth/callback'
    | '/teams/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/connect-bank'
    | '/dashboard'
    | '/home'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/success'
    | '/teams'
    | '/transactions'
    | '/auth/callback'
    | '/teams/$id'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/connect-bank'
    | '/dashboard'
    | '/home'
    | '/impact'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/signup'
    | '/success'
    | '/teams'
    | '/transactions'
    | '/auth/callback'
    | '/teams/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  ConnectBankRoute: typeof ConnectBankRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SuccessRoute: typeof SuccessRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-bank': {
      id: '/connect-bank'
      path: '/connect-bank'
      fullPath: '/connect-bank'
      preLoaderRoute: typeof ConnectBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  ConnectBankRoute: ConnectBankRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SuccessRoute: SuccessRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
